---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak-charts
      version: 2.4.3
  interval: 1h
  values:
    replicaCount: 1

    global:
      storageClass: nfs

    auth:
      createAdminUser: true
      existingSecret:
        name: keycloak-secrets

    ingress:
      enabled: true
      hostname: keycloak.infra.hortafcul.pt
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    postgres:
      existingSecret: keycloak-secrets
