apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
# iV3FqeTzNENi
data:
    admin-password: ENC[AES256_GCM,data:WuZOZWZYTTlblPD7A+UgGw==,iv:xJBS1VyVKSidpmH+9H/P+8NXbb25nWoIec+PdONSdU0=,tag:rBNDCZGqrSPvjBrRXr033Q==,type:str]
    #ENC[AES256_GCM,data:cwGc0MlcO1ThDsqFaA==,iv:bI2JQ8f3b22CkOEnVf1f+YWPuMYeYA+Gl/V8In5EB8Y=,tag:3CA1FnyN2flCaJev/rT/ZQ==,type:comment]
    management-password: ENC[AES256_GCM,data:WeMwCG0YS+cQX+YbivgFCw==,iv:vG3AkxDVLEWxEAJQ75EyyC7o4BFKXzEdKB2nUjVR010=,tag:Rzn7SPPHMyv++R+aJBeI5w==,type:str]
    #ENC[AES256_GCM,data:vHnvfSbMLTlY5BgEXQ==,iv:OTWwW0tWeOT5rN1Fly21v3yCtL2SpXSJeo5IF68tKtQ=,tag:HIyRRntDqE3JT2k1oOwoAg==,type:comment]
    postgresql-password: ENC[AES256_GCM,data:5sDfoq/IqP09baD0tLozSw==,iv:WAL16R7hAnkXxYudQqvJnHPMyvQ+0H88f02NyxrksGU=,tag:RMpZuyrblyr9Agwxa2pMLA==,type:str]
    database-password: ENC[AES256_GCM,data:hFgCjXW9KRndekQmkUmvKw==,iv:F3+Cijo798+FN3tyjvWzeGLdh5kmlVKpS/xX//sxJvI=,tag:fcHc5IvAvj1ShZYJcwNMgg==,type:str]
    #ENC[AES256_GCM,data:pq8pEkV4CGi9PDy61A==,iv:uscR5J1BGO8r6T9AXDV5BC2t8c3uVNxphMu1z+LAm5w=,tag:soeRWQP2a7zcUd1jNAy9mg==,type:comment]
    tls-keystore-password: ENC[AES256_GCM,data:Qiss6o5RjwDmhs+antTCxA==,iv:LG42xueI61azhrVLriLUzg4Jqn0RC9mqLxm7KKFqLrQ=,tag:VvF1ZL8T3GWqcuQ4HRjqGg==,type:str]
    #ENC[AES256_GCM,data:1rMpnckwm2nAZHe++w==,iv:sM4x1OgjUnxU6k+dZMGOpFGBtuzWsdfKMLDNdNC8cAA=,tag:JItUnOnzNLGFkX+BrO/F4A==,type:comment]
    tls-truestore-password: ENC[AES256_GCM,data:jZbi9vBiuIfzNChwBCYmCQ==,iv:97uRA/4bFKOnL2+/ZJtBudKfDvbIJra35j50oi1rofg=,tag:z+Io8UZi9F7fTecmTqIH3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-16T22:58:30Z'
    mac: ENC[AES256_GCM,data:6fPelrMld19PR3cXYvI4BcWQ9jtO0Xqt0j3x3e/5lftN8V6ols/YmmUp2SclwRVA0JcByN7jcxFPhXb9CfLzdPqP4Qk+YV6nKizhyHeF5sPiOm1lpOmmzN0wgFWHfIG/1R2ZK7Uy9GMyAAh1DQafKnE3SuS83W6USacHtTgJl5Y=,iv:aS56CNlTWCFYwcCN/JdLYh1UFg/0Hao7AQOTIIjfM1o=,tag:sB+JfZ9L8gYkgK8bcowNtA==,type:str]
    pgp:
    -   created_at: '2021-04-16T22:58:29Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7C6ZdcckODLARAAjUL0XupB81IDxPE7vpnO8fgKU4JTYU8DOWW3/69wVE46
            dQXkU83MNQO50mWceD3nAc2KSDEKMXikfsuNmSQDrutIjBXw1quNwRBi3MUAnynt
            fu+oLUDFjDUMI0Wl7fMD4P5GV7YFaDxitzNT2e2oVa+JjMOTOrBZqIwb7JIrB5WY
            fe6sWy8p3WLySMZn1iAsbkG5v4sAMo9bJzSytfb7nR/Ue2xXks+Zgx/kXiDhofOK
            N+PJru+BBWCDNkiDuVzq4jQ/DGLGHFUbrP9M5suF852wNn1bwxqgF2W03aEOASTD
            4MHv2oFt3xurOgd5pDVYeIHsi+VO5TLZpyQwbVh7WnyrZcEAee7ytEURabaiIzUU
            PDhd7pXYK3Ifxasy+/T3FgOfpDEUL6sUv2MHabStkOy7d7wRTZWwu6c2ALLBhMLu
            uHSCEDjl5xjXXs7qLq8FPRVv1YNKCTGRMecnuWHwX3SM6/DptChlfKgZoLVRvDAy
            iSorSduoPtVl3x5ZEx0GZ/biyfBH4fxkNq/ZEQTfLQFR8jzDlGjIpAAyWqYUaVJq
            5Y2ZY/dMgH7V6tf36b9gdE17BAfFdOOsaGwhFDBXrV9w9DWsQj7GSucjEbNwYwpH
            a/mU2nNYRQcN5eq0CJFuZm7L7QVf3QvQ2slK9UjPEeuH/RmjlvvKo8cnOsrym87S
            XgExI6R/NMMxlOIPLN7E6WNbX5yp2XoPS7bsB/NhlOxH80D0bG7PV6SH8h1fupI+
            zB+XDNbmhkzIxJX9hZVmT7A919+pPnm2kaa82JCnEQB/FrjgA/ba05zGu0rY/2U=
            =7Hg6
            -----END PGP MESSAGE-----
        fp: E357B3731E9AFAB4FCF87A0CDAE80E930711EA3A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
