---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  path: ./main-cluster/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
