apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      version: v4.0.8
  interval: 30m

  values:
    nfs:
      server: 10.114.0.5 
      path: /srv/nfs

    storageClass:
      create: true
      defaultClass: true
      name: nfs
      allowVolumeExpansion: true
      pathPattern: "${.PVC.namespace}/${.PVC.name}"
      accessModes: ReadWriteOnce

