---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: fusionauth
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
  timeout: 3m

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fusionauth-postgresql
  namespace: fusionauth
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
      version: 10.3.17
  interval: 1h
  values:
    replicaCount: 1

    postgresqlUsername: fusionauth
    existingSecret: fusionauth-secrets

    persistence:
      enabled: true
      storageClass: nfs
      size: 10Gi
