---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fusionauth
  namespace: fusionauth
spec:
  chart:
    spec:
      chart: fusionauth
      sourceRef:
        kind: HelmRepository
        name: fusionauth-charts
      version: 0.8.1
  interval: 1h
  values:
    replicaCount: 1

    database:
      host: fusionauth-postgresql
      name: fusionauth
      user: fusionauth
      root:
        user: postgres

      existingSecret: fusionauth-secrets

    ingress:
      enabled: true
      hosts:
        - fusionauth.infra.hortafcul.pt
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    search:
      engine: database
