---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: fusionauth-charts
  namespace: fusionauth
spec:
  interval: 1h
  url: https://fusionauth.github.io/charts
  timeout: 3m
