apiVersion: v1
kind: Secret
data:
    email: dGlhZ29hZGlhc0BnbWFpbC5jb20=
    api-token: aDZiOWlsS3c1YmxockZEYWpNcHNLa25QNTlTZjAybzlXZ1ktMHB2bQ==
metadata:
    name: cloudflare-api-token-secret
    namespace: default
