apiVersion: ENC[AES256_GCM,data:++0=,iv:6vZ6d7HD2eKZiMxoZE4B7Jbpdfv46+IhMajGsPrB8Xk=,tag:TCAkd8r6dv3Xq/I6C2AKEA==,type:str]
kind: ENC[AES256_GCM,data:n1Kv7hW+,iv:RNp3E3imn1zbFpTL1bC9yLl0JYohJLZ1dCYAc/socP4=,tag:tuecsHpd3hXyP6hIKO7w0A==,type:str]
data:
    email: ENC[AES256_GCM,data:L2bJM+2ZFfB91OZafPG3N819co8=,iv:DfHKoROx3rJN1QyGSmzYqSDPaKnH+rVxpF7N6XwRdpk=,tag:k8lrqSJIC+SE8NvETLSkEQ==,type:str]
    api-token: ENC[AES256_GCM,data:Q0xYqcyXbxt1CZK+48HyDpv8c8wNv46DPlkhHNDHb4o/yWIevOljxg==,iv:9/69mREYB7/+ISYsI61msNAxB1wgka3oxGkL+tNyfzo=,tag:eWI0/jHcRFBDD7sVfdRjoQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sbEpYof4iidLq4/zCmU9t4aYo+GEJPM2MRup,iv:k3+c3CvhYG3apkJUtqsMVmQN16WjoMLPuz4/2Qr+wCA=,tag:0JZghd+KyyzsxL1NMRFy7g==,type:str]
    namespace: ENC[AES256_GCM,data:u5e4eGHwcQ==,iv:pWznxlvwKpRdi7ZQWdKXamHzfGDtpbUAs+Yo88913SM=,tag:hUFyMuCe0xNsxMyMTewvag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-14T18:53:49Z'
    mac: ENC[AES256_GCM,data:E3BZaqbh+l7Ws4q4tS+W0kAZqmoB+z/vPC8XwNbu8dFa3zSvAvb8AooOvX+4pP8xzbPe+bO7AtnIxgetk/Aw3nbJu6BPhoor8JlbHtxbhrAwi5JZQzp5Hq7lNNmg8aPXqID8GRHvg0/l+++MvFScm1q7pvyfNwOM/w3klUSu3Gk=,iv:vfEILIGf4Re2dGeVbVZAwwK9U5Hpg4C7Fu4J1EKVoNY=,tag:eQxgRNRR5xTLVYUc9ANTdw==,type:str]
    pgp:
    -   created_at: '2021-03-14T18:53:49Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7C6ZdcckODLAQ//citd0Eonhe0Lr65khve86g7v60RN6I+80Oc9eQGnI0+w
            u6hOxNJf7p/JkvVs4p3GRU+FFFdyu2ZhsVROkByxdIDqgotNU5LAkdh9cT1lhUvu
            KxPL8oK593Vh9Cp9LGVGYPS8rbCXvvug0N5qXZA5ceiRIuaDFb9Meh3hpblwq/gp
            h/hFErmlExf5NvTGes9iFZ6paf5eNqhvEawLauz6UMlzED/WJdLsuk9qZoZ2F503
            fcCgKN5lidmQWbAzmYV/jGPlmY5TvKSoTSBl/nrPBqAtPfF08P5MhrRQxIFgaXW3
            h2/7dpq4svyk6tEQnTpM5PGs4LOpdLbkCDx9E3ZOLP4Jy3SLKLFTBhDWMBKG3YOs
            GKnqFiXoH/+oA/hRezXacbWAXx8mToaMGhXZz770lX6cem3DCAI0iP7+ozDvWlvq
            efepp1ixpywYZc/gPFwXF29CmPai377sVHY7RU65OsedKC1AKWv3zz0BZOMuesey
            pstUQFbZKzhnvzS926a42F1NPxr2hD/nvjxRBBWlUQHkHxn2hmJcgtBHk4Jx9iYy
            kEll1SjcF9qdnMNgRdwyNPQIBmdUJl//3fEhT8+qk/A+QJu8fCwjuA7KkfWuHTPF
            kL8ortVSqnLvgYqCCuIf0JSgRD5IbOJRyHUf7WCxAbm4bUFGikrBmjJtu7i8W5nS
            XAEzR1v5vunXarYzh7FcbD+2Cv71MLl9+s+Jj2vjk+SVo+JQmpHAzlhpVnqquq5u
            ZWYVkiTjhSx0I75svYhECQ9prj0cmFSRlca6u82B3amM6kGcmjwv+Aeme/zE
            =NiqJ
            -----END PGP MESSAGE-----
        fp: E357B3731E9AFAB4FCF87A0CDAE80E930711EA3A
    unencrypted_suffix: _unencrypted
    version: 3.6.1
