---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sko-ai
  namespace: cert-manager
spec:
  secretName: sko-ai-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "hortafcul.pt"
  dnsNames:
  - "hortafcul.pt"
  - "*.hortafcul.pt"
  - "*.infra.hortafcul.pt"
