---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-server-provisioner
  namespace: nfs-server-provisioner
spec:
  interval: 30m
  url: https://kubernetes-charts.storage.googleapis.com/
