apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-server-provisioner
  namespace: nfs-server-provisioner
spec:
  chart:
    spec:
      chart: nfs-server-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-server-provisioner
      version: v1.0.0
  interval: 30m

  values:
    image:
      repository: quay.io/kubernetes_incubator/nfs-provisioner
      tag: v2.3.0
      pullPolicy: IfNotPresent

    persistence:
      enabled: true
      storageClass: "do-block-storage"
      size: 50Gi

    storageClass:
      create: true
      defaultClass: true
      name: nfs
      allowVolumeExpansion: true
