apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    users_database.yml: |
        # docker run authelia/authelia:latest authelia hash-password 'yourpassword'
        users:
          tiago:
            displayname: "Tiago Dias"
            password: "$argon2id$v=19$m=1048576,t=1,p=8$SW9DY0Y5cHFSSHZWM3A3TA$PuqcY+7wWe+ri4lI64tkxbYMBVGbuD0/iM1FPaW+LV0" # paLxEsfQA2LE
            email: "tiagoadias@gmail.com"
            groups:
              - admins
              - guardians

    configuration.yml: |
        host: 0.0.0.0
        port: 8080

        log_level: trace

        jwt_secret: "HEAG_drug2wox*touc"
        default_redirection_url: https://hortafcul.pt

        totp:
          issuer: auth.hortafcul.pt

        authentication_backend:
          file:
            path: /config/users_database.yml

        access_control:
          default_policy: deny

          rules:
            - domain: 'hortafcul.pt'
              subject:
                - "group:admin"
                - "group:guardians"
              policy: one_factor

            - domain: '*.infra.hortafcul.pt'
              subject:
                - "group:admin"
              policy: one_factor

            - domain: '*.hortafcul.pt'
              subject:
                - "group:admin"
                - "group:guardians"
              policy: one_factor

        session:
          name: authelia_session
          secret: "FLOX@spaw2pleb9vaic"
          expiration: 18000 # 5 hours
          inactivity: 300 # 5 minutes
          domain: hortafcul.pt

        regulation:
          max_retries: 3 # more than 3 requests...
          find_time: 60  # over 1 minute
          ban_time: 300  # = ban for 5 minutes

        storage:
          local:
            path: /config/db.sqlite3
