apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    users_database.yml: ENC[AES256_GCM,data:0yMpnX/oHH7dBakFqFu5vlO2bjS4/vBxKLve8BBvJ/pf2cGIBP7ZMvWosKUI+KdisCGMb9X+z61MJPSEASvK3GETHpbnp3v09oXFiMRsx+iK0qEYi33yKBdhFd/by42COlu10nNAxfd3N6VxnId06CJosEV4FPxdv6ASX7x0QkUk3sDY2apu3rAAcvMIfLyJ1uEyIOLEy2yfLwemUKMkxfQQ3aR37ZfmFqXaGpMDxqRE6c5CPnOUx+iflXyqRy8xrFgfYAK7t8WbS7M9aWRm6nLA0ZKaQPzddTNjFutquHxXJ9jxyZOM8B+GmpKZCvGOLnSI/kx/BJ46XTZlTEuXPb2Ck1V5zNoz7pMOCMKPi0by3+XOa0FGCeOVNvJwm9ASX93klF0ZtFRJZ6VzU1rEwAcy+ulDZlmK/X4hcSSgOkdy2XhRVzCaTRFhfOs=,iv:cFwhqYF8ydgSsK1dlAdYjW58kgC3qISYsdR8VVxFXVM=,tag:u8JQtWxggJlw6Hpf7Pom2w==,type:str]
    configuration.yml: ENC[AES256_GCM,data:B2cgHZh4hAyPsAVrHwT0JtxbqsMQUmlomzvKV7D29he2e/XoZn1pBdTf0theO33kpWITde9FYJ2q0+1qV0eZ9hScp2x/qgUChicOWe+g5D9FRdc0htbfR/x9AteBZvnLQOJYBRthFfaUa/Vvlw3htN62lTmRSUcIFJzmJ8Y/+XC9hrmEZmWndPpAtwRXBqBkW90qYw+/C3IIUepsKKcON1hJDMNGzoPsJCl1Dw8hUCB+nzGN6xVd4DsjdRyIyNeCXXhJrncLMregPl8YKENPFvvG4ujC93HAOd6DNCnAp7LMCkVRuAH5DYLyaiok5CLhkTFKOLoqm9Z+yGbxhxCKfGnfcxLYKxvRHc0mfoQlNhrAbHrsoZujNPl42Ofb4oG9saT5B9gmk7a3juFEbCGAzXDiQHxGyJ+5viXaOHk7uhyDvwH1po68WYliURTzFzKYKdq3hTmiAerFlbvmBkEPHDRKzouMi5XT3wm+E7qNntA1wKQLuaPive2nZ/ZbtV7ZvQIG5h5O5rnvDzQcJypXs1Wd8EqUlqmwcb0DNPQBwPJzld2BSfgw+mA55jN1A88zM/01y5XzID3uKH+yvM/MHoLH5lE45su2ZoO1jp0bQQ64HYaRyvmunLpnNjL4/lHU7VXdgDpiYkdqbq3lX38h2LrOwO8S6Cfoqfh/+K1+P5OmpDjF/tZ2JOXQK15ZhHoNelYInUC5zjCzQKQh2IoGRToCpYBAn/i5n+NODtbG+ZuSl+Ndqv1SJuzFI6eAODAHGwDs+1a48jgbpfgwFRC5kctzewHbcvjyV3veers3afEHiyxNims043mQu3m1ToWFs2HLKyB19ccUtSQGBQ9srW5CRdxE8xFa2qRo3CHZJLYsVVbfU+5OrrEskUF/DeSG3dirSTCS53yFXBEkCIDuPRDsA1h9/YR+qmBrxu+dnYXVqdddCyv7M7ipCZUI0T2M6X3aULyjQ4m5oCjQQX0E53wLc/66NWHNM+DqAMmqk7rhvbcCevoKtBDYZ9dDtzsH7vBUsTWacCAGgpwInhZT5WZ3666oJGD1UsUf8SHQ5zx680xBXyqKJuNUVsPhadXWCXkN9qdcl/YtIb1ZU2DfjTS7xmKrkGdvgumVt4SAH0MmeF78jvWhE1HS7NsbFtp2D6K7S6ngIn5JErB8bOuBVWLYgNijanpMw7i11AcVdtw+lX5e6wVTa/vQNhmIJi/OcIIEkCdV7Kf/n6lWql6jgtM4lNkJ9Ltk0ebO3MZ91UYjvV+ciupB+K1QEvqp9DT4x46UujZ0QiaN0gQIVvVNDnlYVzhf0Z4GOA6W/HInSIAgpTyEDkea1R6sOos5WN4GohCIizhZIuw=,iv:PfuvQqg1P7MY7GVwpWxa6uJG93BhsBxVdCfH4It39L8=,tag:HPQ/LvN7zZeJ6LZZpfP8BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-03T17:02:42Z'
    mac: ENC[AES256_GCM,data:hr8giKYa50qV8pTE7L5Z+COQwRrWGfGMWoksWCoE8I+lTvSxDfHyQ+e5OxS6V0dtcs9rYIl5eV1LAjY+6B7Y3FvciDYW/EUTH3ZVC8heWsXmFrx7GhSwAK6kEnb0HJLZP8J+tEXWAVa4MwxtgLqXs7adJcsMvC3uDHqAu4oOQ/M=,iv:KBAeaBM1IEw1b0yjfNLyBgwHV6QWINPWHRnCjXWPOHs=,tag:aHOlxUrUV3TdIx7xZagTcA==,type:str]
    pgp:
    -   created_at: '2021-04-03T17:02:41Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7C6ZdcckODLAQ/+LfxezigsDJtXmCEMbYI+o8EFcF+a1bJxwL9Svhi6R9FQ
            077zkianhpVfuU/975wBLMVnoyKgJ28O+qnwvDl4YLyysPcHhmVtyLjT1bnO/FdP
            5Oeeq6FJceWZkRn1y+NZhCSvMnYYCCimIHhogjEHmbwf5BNNFSZGTtIT0+HnUOxg
            cfjYHa378NbmFQdSxMx4IodcDKq7tgv5ry6VWsqCKtQCPCLcD6QMojFQ3QE1ZVw7
            pTejBZfIskeYhRjMG3gwG7jofQfsTJ06pH77M6HHQJlW3cdY3f2+LjQi0JKY3G4+
            nuz1qG8gRkWUesdw1Am3hRMfh2T/dy2tkDhFpDCN5AE0XTWz0cTN6lQrk/VzP8VB
            fskoiAPdgNTUxPLmZCMKaST14h26fDcUy5Pzw0u7KQilnDz5xCGdfUFzxJwt/v6B
            QZ7zXNrWJxnn0X1OVqodBJd0xo/+HgheUgwPOZLs4cVglSHHCzG8tTTFqBEXWH6u
            bFjlA0aLlu/TGLMQb33LoR99DzJCoRKV05r5Jlk/npbsJK/nE6inTWzqvaCbrJiA
            ReT4+vuAwbTPfg9xRTAR2Bk0gvUNCM97EKQ+Gdrm758wFf9SYeBtoJtdqn3yOz48
            9cqfFkDWMZm7bqr663AfQWPINNusctGoke3URQ/X9Y1DNCF8Kxbe8YNFzIrazqDS
            XgE7kjeO0/8oSBekzqs7NfT6y5svVDt34qaLq4fmP0EaGXYetA7Jp2dmqyz3zjy3
            6hTRIJj6vSN8O8xV0wi/aMOqmv4j9dIZcDvQxIjMpKLtZhtHrMIwjxQlGx/8DP8=
            =Mf7Y
            -----END PGP MESSAGE-----
        fp: E357B3731E9AFAB4FCF87A0CDAE80E930711EA3A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
