apiVersion: v1
kind: ConfigMap
metadata:
    name: authelia-config
    namespace: authelia
data:
    users_database.yml: ENC[AES256_GCM,data:Ei11h5+/++grIIuFE3XuzSa38VHkn+4kH+WXSph7PCOiQ7KdX0WUTaJ3m32V2FTf+pzNmGgy5mN8wPDmjI9q8L24ejFJMfrACH278m8Xsi06lBFy7utrnE00+W19F7DMk1K280UDo+sxeDPYHEK196BYHyAEr+qJxM9sJWYp4dMLro8oBtCqRUVQZ0j3B03QNCTgX3+dpICYCvh8yzbel/W1jrMSuGIoPsO5yz7WoBQuot2jRkbN5OThA4WPyvzq0h3Jjar/dDwO9PJUdy6cOtQC8BpDELuLKPVpvICK3R0b5j2XaN4qam0F3lzkxGQDE7dV3W7XMEM1Z7C9umAZ2g/wPVT9BqFMblpjLmfg+gO6emrCRGms1qM0/SE789FCM18OX7DsiHTqwM7xpWX6w1nm23F8nUckkO4tYpW/XNaf/v+HfcSLemPG5dw=,iv:vOAkcOhz9bIUfqOAPBLqPWplMpqbBMvdUIHgXVnzvFs=,tag:AvCMSJxmNP7IDzHeNsBIKw==,type:str]
    configuration.yml: ENC[AES256_GCM,data:cI55z2pEvanrnDFO7UfYXOokbDwqeCQHvv69/RBJ0IrRDO2IbpXQ+OEovw3atLlH309q+PrwXAnhsZmsdW+tm9Ly7UYd31x9NfhZfZT/YKorzEzUveQcry/PdFUwGx8sNpXM0PJZ8QX7Nx2KivLsNzPPy8wGEijSSEyeuZaBuYSzeuaNUaI9SNmToFZv7XlHNeEijTjhVWZbyppQ1TlFRtrfrOzY4NFzn37b6upuTUwRRlWiwGqg1m3zO+H5NtTm+KUqwdCDa9mRZ/2E0tZYAYT05m5a1ZCBEjKgGqADijtLKha9ZMrQXEPX915CAotnbgFtkP5Do+GmrPLSSpsQVvJHImdn1vJGjUX22xo4WtbQdKkNBmwybf9ObdA5pKk98XD/lCGNWDj8ygfWTP3q0HFG8tzaVMfHXOnHcP1pMLvApk16crCCc6ARkT/biIxm8L2kfk0x1FiiIKVl5aKe9DkWFVDDkSpmUrVFVHComEt5V6/UXN+MWhVRtEG8ydBsx5/lvqXid2szHA07v9EoEVxV5SAVDC+oC0q7dy0t7IvtEO44PxEH7XZr4jG15xvcJgC7zIcHA14R1kfafnFU6RCgwVavHq9wE3dJNaHYWgelSC1ki5qzX50tStqvlB5I4Wvj95IDk6SBVmMRsHQEUB+Fhprt+72GC0/sirwRgyZTEvJWgdhYgvgpL7nVUrtGqKo1f+NGg2QGrfO2hivv3Kb6gbq/gWzMgQbpt4HgEfhEXMCoWYddtBuMXYAjsfz6ma3YRLixFpmYjoxcNEaRXtRB16MLq1cWi+y6Lxz32a9eylBYXUt0CnHkKN+yi18uk5KP3/ePGabhZVHOlteQtiB/3fTXNj3nwP4cnYG9j5ZRnWOVCZeovOU4pbg/aioLiVDrx0/HuUO2MxD1N4hyblZkBGK+WrStCc1Zz4s87QwpGRhMKY0G9Fspy0KYLpzZKJI2Ug9a91J+gpmvpjfmUBveKYUPt9i8voWSQI/2uAwOyfV5I49rpx8ta7deMj+mAkI/U7MIAUrfNU1QGsrGnt1PNZR6ZYGmPCdZi8QUtaRQQHX4KUYii062+cjnusrRNz47pqjzAh4HS2lBzgLL5Hw11hUEBrp+te1e5eZvmZQFEvD7Fklvady/pCgd6Wef3gqedvjQjU14JJaHsoF2L+CSUOP1E+osHPR1jeizDQRGkXTptkePmnvZ+Oa7OwimNnR2GPNbCECfXbqUEJ2qOEPiPFWBnaUq9Mw9tHoQwLsM/dRAyTSlkjo5y4eTN61sh17sj+P3jSXuIdrxtzVz4ITD6F65W5OaIcjt5F0lsEWwjD1q1zXd7amCgWzfAqCgj42Vp6mjpDmKChm2ni00gXUMaKQD4JVNhS3IWYKCh66N5ytHsVZIUTbINh2snKV/Ql63sehh2XX+0jBMTIupMgQnyJhRJDt1A0cWrT0tY0nd8zimOafKuBxgayGW4eM3+6lCY8aq04jMLqiW8P/k4ydDSJbiqSscax5mMnD3yxt5oVe61SmUud/tbQtBhRRCTcK4dfzWlPCVaBC+RfclrxT/72eTVensy5fEBYvCExkSfZy2pMo68W7Q0V2oXh+VfeMkga15AFEYiQ18/PJ4xIBYCFh/DA1LYVyhIM4mFbATMzjdFMO30BZeWK73m9scWQMyFIQ3+RZxRWWJEtP5oVH3SFsUtN0Ef/g9i4cxw925t+EVJmk42pu7oqUqMga6nKeJsHP58O8S9PCL2YyPhpxjVNCzdh92gIgZqsR+sA==,iv:sAdZWlOGBCmkdOEkcve2Y3mK4eKd/YCpCXBHqnDG7F8=,tag:sIfzfWiNtnvNyGVmG8UQ0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-16T18:34:11Z'
    mac: ENC[AES256_GCM,data:DJnORUIpvKOKLt0xcCjHdhKllqOL6F0EUzRoaIoNsJYvn3DZ2RJen1DuugGZmi/mbNA1vARGwcSxm97FFD1Ywuw686gPPa0A7vvWUuC1/EsBWkvnA7EWG+Fa7gAfDGIDVrqfj5bV918r8r+dwNPWSmCNCr9bTo07yvS8Wuji+5Q=,iv:gnBCCwTg9tKQODUg9jumbasSYs5qO+cbM5qNzCigGL0=,tag:pTzooPqAo5MMKEqWSHR9OQ==,type:str]
    pgp:
    -   created_at: '2021-04-16T18:34:11Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7C6ZdcckODLAQ/6AxDGYvpp6IN7B6lq5rrUKx4W5HcZq53XVrd+25BSIJL6
            30cSk8yYqP+GOm3rI5JXInEpXj2aDXoywuAZYDmZFqBdi9kXG2f2uBGk8Uw667vK
            pF7GzKj8WUlBp0XDhsd3PKr4R0Iqajl7XMNKcUEG0iL+UTu+g1j1xoNrafx5qJSd
            Yky90Wyt08pFk46iVczS4HBiju+NqUNodIqYPZNSLA/hm3uSIfGIgV0B6q3KJlsY
            YgkkV6cpb0QA/yj+HrmCYUG8V3HvghG/UGxco3cgY+WjnMwr/CS/v/wHV7kO9VcY
            1DvzmT1H3VkrJu8qqaVHJ4PzQxsOlbCtSGIsW/NFT6Aeo7fJliY23WxJ2wm3ulxH
            mbgrsQ2NmrXrMF3V0R7+2Dvt2r0VzeoZ4fFks+1uYxnaXtcOJz5rAyic7sq9Xl6R
            UbDvVExx0Az8t38wXPlCgw+49sI4LduO1pPUvbChU4sTdvZyXaeUVDx2myfXddRY
            IJA03ZVq3IL7IcwHkzYCzJjdiXnyluqmvLp/uh1gPWZgHuK38tjWSSAqd8hXNrcv
            HWbCTNbjtU2ABRSGs+Yh6NZ3FGj7PLODbqZMGZ5eEQRQAjDuwgEZd8+3tXWPHS1v
            EtGQQ+MFNPrKyRwSd3fQdTCTmhzk3nf+aQM1dTd/oRJ4FRf4sUkR6eW9597YDvnS
            XgHNrWnhNdVTapbWl79PWnix9tWWG/sMjtZVo1fFfYoFsXJxnzb/byISi2OWVvb4
            ZBsPxUQPKyCt3JgwbwvowCCTpNX3v2zZTdyaKYLrdxZitswdEbVi7FPQFFyAB9s=
            =Wi5G
            -----END PGP MESSAGE-----
        fp: E357B3731E9AFAB4FCF87A0CDAE80E930711EA3A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
